# Site settings
title: Mike Porter Blog
email: Porter.Michael.James@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mike Porter's programming blog. I write tutorials and information in a clear manner that I can later reference.
baseurl: "mikeporter.tech" # the subpath of your site, e.g. /blog/
url: "mikeporter.tech" # the base hostname & protocol for your site
twitter_username: mikeporterr
github_username:  portermichael

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude: ['node_modules', 'Gruntfile.js', 'package.json']

highlighter: rouge

plugins:
   - jekyll-paginate

# YB Settings
excerpt_separator: <!-- more -->
paginate: 4
comments: false
